name: PR Check
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Branch
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Run lint
        run: ./gradlew lint

      - name: Run tests
        run: ./gradlew test



